export const TYPE_USER_GET = "GET_USER";
export const TYPE_USER_POST = "POST_USER";
export const TYPE_USER_PUT = "PUT_USER";
export const TYPE_USER_PATCH = "PATCH_USER";
export const TYPE_USER_DELETE = "DELETE_USER";
export const TYPE_SET_USER_STATE = "USER_STATE";
export const TYPE_USER_SEARCH = "SEARCH_USER";


export const TYPE_PRODUCT_GET = "GET_PRODUCT";
export const TYPE_PRODUCT_POST = "POST_PRODUCT";
export const TYPE_PRODUCT_PUT = "PUT_PRODUCT";
export const TYPE_PRODUCT_PATCH = "PATCH_PRODUCT";
export const TYPE_PRODUCT_DELETE = "DELETE_PRODUCT";
export const TYPE_SET_PRODUCT_STATE = "PRODUCT_STATE";
export const TYPE_PRODUCT_SEARCH = "SEARCH_PRODUCT";
export const TYPE_PRODUCT_SEARCH_ASC = "SEARCH_PRODUCT_ASC";
export const TYPE_PRODUCT_SEARCH_DESC = "SEARCH_PRODUCT_DESC";
export const TYPE_PRODUCT_SEARCH_CATEGORY = "SEARCH_PRODUCT_CATEGORY";





export const TYPE_CATEGORY_GET = "GET_CATEGORY";
export const TYPE_CATEGORY_POST = "POST_CATEGORY";
export const TYPE_CATEGORY_PUT = "PUT_CATEGORY";
export const TYPE_CATEGORY_PATCH = "PATCH_CATEGORY";
export const TYPE_CATEGORY_DELETE = "DELETE_CATEGORY";
export const TYPE_SET_CATEGORY_STATE = "CATEGORY_STATE";
export const TYPE_CATEGORY_SEARCH = "SEARCH_CATEGORY";
export const TYPE_CATEGORY_SEARCH_ASC = "SEARCH_CATEGORY_ASC";
export const TYPE_CATEGORY_SEARCH_DESC = "SEARCH_CATEGORY_DESC";